import Product from '@/componants/Product';
import { Container, Grid, Stack, Typography } from '@mui/material';
import Head from 'next/head';
import React from 'react';

const NewProducts = ({ products }) => {
    return (
        <>
            <Head>
                <title>Products</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Container sx={{mt:'5rem'}}>
                    <Stack spacing={2}>
                        <Typography variant='h3' sx={{ textAlign: 'center', color: 'primary.main' }}>New Products</Typography>
                        <Grid container spacing={{ xs: 2, md: 3 }} columns={{ xs: 4, sm: 8, md: 12 }}>
                            {
                                products.map((product) => <Grid item xs={2} sm={4} md={4} key={product.id}>
                                    <Product product={product} />
                                </Grid>)
                            }
                        </Grid>
                    </Stack>
                </Container>
            </main>
        </>
    );
};
export const getStaticProps = async () => {
    const res = await fetch('https://dummyjson.com/products');
    const data = await res.json();

    return {
        props: {
            products: data.products,
        },
    }
}
export default NewProducts;