import Head from "next/head";
import { styled } from '@mui/joy/styles';
import Sheet from '@mui/joy/Sheet';
import Grid from '@mui/joy/Grid';
import Product from "@/componants/Products/Product";
import { Container } from "@mui/material";

const Item = styled(Sheet)(({ theme }) => ({
    ...theme.typography.body2,
    padding: theme.spacing(1),
    textAlign: 'center',
    color: theme.vars.palette.text.tertiary,
}));

const Products = ({ products }) => {
    
    return (
        <>
            <Head>
                <title>Products</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main >
                <Container maxWidth="lg" sx={{mt:'5rem'}}>
                    <Grid
                        container
                        spacing={{ xs: 2, md: 3 }}
                        columns={{ xs: 4, sm: 8, md: 12 }}
                        sx={{ flexGrow: 1 }}
                    >
                        {
                            products.map((product, index) => (
                                <Grid xs={2} sm={4} md={4} key={index}>
                                    <Item>
                                        <Product product={product} />
                                    </Item>
                                </Grid>))
                        }
                    </Grid>
                </Container>
            </main>
        </>
    );
};
export const getStaticProps = async () => {
    const res = await fetch('https://dummyjson.com/products');
    const data = await res.json();
    return {
        props: {
            products: data.products,
        },
    }
}
export default Products;